const LotteryABI = [
  {
    type: "constructor",
    stateMutability: "undefined",
    payable: false,
    inputs: [
      { type: "address", name: "_whbarTokenAddress" },
      { type: "address", name: "_randomGeneratorAddress" },
    ],
  },
  {
    type: "error",
    name: "OwnableInvalidOwner",
    inputs: [{ type: "address", name: "owner" }],
  },
  {
    type: "error",
    name: "OwnableUnauthorizedAccount",
    inputs: [{ type: "address", name: "account" }],
  },
  { type: "error", name: "ReentrancyGuardReentrantCall", inputs: [] },
  {
    type: "event",
    anonymous: false,
    name: "AdminTokenRecovery",
    inputs: [
      { type: "address", name: "token", indexed: false },
      { type: "uint256", name: "amount", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "LotteryClose",
    inputs: [
      { type: "uint256", name: "lotteryId", indexed: true },
      { type: "uint256", name: "firstTicketIdNextLottery", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "LotteryInjection",
    inputs: [
      { type: "uint256", name: "lotteryId", indexed: true },
      { type: "uint256", name: "injectedAmount", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "LotteryNumberDrawn",
    inputs: [
      { type: "uint256", name: "lotteryId", indexed: true },
      { type: "uint256", name: "finalNumber", indexed: false },
      { type: "uint256", name: "countWinningTickets", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "LotteryOpen",
    inputs: [
      { type: "uint256", name: "lotteryId", indexed: true },
      { type: "uint256", name: "startTime", indexed: false },
      { type: "uint256", name: "endTime", indexed: false },
      { type: "uint256", name: "priceTicketInWHbar", indexed: false },
      { type: "uint256", name: "firstTicketId", indexed: false },
      { type: "uint256", name: "injectedAmount", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "NewOperatorAndTreasuryAndInjectorAddresses",
    inputs: [
      { type: "address", name: "operator", indexed: false },
      { type: "address", name: "treasury", indexed: false },
      { type: "address", name: "injector", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "NewRandomGenerator",
    inputs: [{ type: "address", name: "randomGenerator", indexed: true }],
  },
  {
    type: "event",
    anonymous: false,
    name: "OwnershipTransferred",
    inputs: [
      { type: "address", name: "previousOwner", indexed: true },
      { type: "address", name: "newOwner", indexed: true },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "TicketsClaim",
    inputs: [
      { type: "address", name: "claimer", indexed: true },
      { type: "uint256", name: "amount", indexed: false },
      { type: "uint256", name: "lotteryId", indexed: true },
      { type: "uint256", name: "numberTickets", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "TicketsPurchase",
    inputs: [
      { type: "address", name: "buyer", indexed: true },
      { type: "uint256", name: "lotteryId", indexed: true },
      { type: "uint256", name: "numberTickets", indexed: false },
    ],
  },
  {
    type: "function",
    name: "MAX_LENGTH_LOTTERY",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "MAX_TREASURY_FEE",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "MIN_DISCOUNT_DIVISOR",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "MIN_LENGTH_LOTTERY",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "buyTickets",
    constant: false,
    stateMutability: "payable",
    payable: true,
    inputs: [
      { type: "uint256", name: "_lotteryId" },
      { type: "uint32[]", name: "_ticketNumbers" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "calculateTotalPriceForBulkTickets",
    constant: true,
    stateMutability: "pure",
    payable: false,
    inputs: [
      { type: "uint256", name: "_discountDivisor" },
      { type: "uint256", name: "_priceTicket" },
      { type: "uint256", name: "_numberTickets" },
    ],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "changeRandomGenerator",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "_randomGeneratorAddress" }],
    outputs: [],
  },
  {
    type: "function",
    name: "claimTickets",
    constant: false,
    payable: false,
    inputs: [
      { type: "uint256", name: "_lotteryId" },
      { type: "uint256[]", name: "_ticketIds" },
      { type: "uint32[]", name: "_brackets" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "closeLottery",
    constant: false,
    payable: false,
    inputs: [{ type: "uint256", name: "_lotteryId" }],
    outputs: [],
  },
  {
    type: "function",
    name: "currentLotteryId",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "currentTicketId",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "drawFinalNumberAndMakeLotteryClaimable",
    constant: false,
    payable: false,
    inputs: [
      { type: "uint256", name: "_lotteryId" },
      { type: "bool", name: "_autoInjection" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "injectFunds",
    constant: false,
    payable: false,
    inputs: [
      { type: "uint256", name: "_lotteryId" },
      { type: "uint256", name: "_amount" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "injectorAddress",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "address", name: "" }],
  },
  {
    type: "function",
    name: "maxNumberTicketsPerBuyOrClaim",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "maxPriceTicketInWHbar",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "minPriceTicketInWHbar",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "operatorAddress",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "address", name: "" }],
  },
  {
    type: "function",
    name: "owner",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "address", name: "" }],
  },
  {
    type: "function",
    name: "pendingInjectionNextLottery",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "randomGenerator",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "address", name: "" }],
  },
  {
    type: "function",
    name: "randomResult",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint32", name: "" }],
  },
  {
    type: "function",
    name: "recoverWrongTokens",
    constant: false,
    payable: false,
    inputs: [
      { type: "address", name: "_tokenAddress" },
      { type: "uint256", name: "_tokenAmount" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "renounceOwnership",
    constant: false,
    payable: false,
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "setMaxNumberTicketsPerBuy",
    constant: false,
    payable: false,
    inputs: [{ type: "uint256", name: "_maxNumberTicketsPerBuy" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setMinAndMaxTicketPriceInWHbar",
    constant: false,
    payable: false,
    inputs: [
      { type: "uint256", name: "_minPriceTicketInWHbar" },
      { type: "uint256", name: "_maxPriceTicketInWHbar" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "setOperatorAndTreasuryAndInjectorAddresses",
    constant: false,
    payable: false,
    inputs: [
      { type: "address", name: "_operatorAddress" },
      { type: "address", name: "_treasuryAddress" },
      { type: "address", name: "_injectorAddress" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "startLottery",
    constant: false,
    payable: false,
    inputs: [
      { type: "uint256", name: "_endTime" },
      { type: "uint256", name: "_priceTicketInWHbar" },
      { type: "uint256", name: "_discountDivisor" },
      { type: "uint256[6]", name: "_rewardsBreakdown" },
      { type: "uint256", name: "_treasuryFee" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "transferOwnership",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "newOwner" }],
    outputs: [],
  },
  {
    type: "function",
    name: "treasuryAddress",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "address", name: "" }],
  },
  {
    type: "function",
    name: "viewCurrentLotteryId",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "viewLottery",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "uint256", name: "_lotteryId" }],
    outputs: [
      {
        type: "tuple",
        name: "",
        components: [
          { type: "uint8", name: "status" },
          { type: "uint256", name: "startTime" },
          { type: "uint256", name: "endTime" },
          { type: "uint256", name: "priceTicketInWHbar" },
          { type: "uint256", name: "discountDivisor" },
          { type: "uint256[6]", name: "rewardsBreakdown" },
          { type: "uint256", name: "treasuryFee" },
          { type: "uint256[6]", name: "hbarPerBracket" },
          { type: "uint256[6]", name: "countWinnersPerBracket" },
          { type: "uint256", name: "firstTicketId" },
          { type: "uint256", name: "firstTicketIdNextLottery" },
          { type: "uint256", name: "amountCollectedInWHbar" },
          { type: "uint32", name: "finalNumber" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "viewNumbersAndStatusesForTicketIds",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "uint256[]", name: "_ticketIds" }],
    outputs: [
      { type: "uint32[]", name: "" },
      { type: "bool[]", name: "" },
    ],
  },
  {
    type: "function",
    name: "viewRewardsForTicketId",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [
      { type: "uint256", name: "_lotteryId" },
      { type: "uint256", name: "_ticketId" },
      { type: "uint32", name: "_bracket" },
    ],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "viewUserInfoForLotteryId",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [
      { type: "address", name: "_user" },
      { type: "uint256", name: "_lotteryId" },
      { type: "uint256", name: "_cursor" },
      { type: "uint256", name: "_size" },
    ],
    outputs: [
      { type: "uint256[]", name: "" },
      { type: "uint32[]", name: "" },
      { type: "bool[]", name: "" },
      { type: "uint256", name: "" },
    ],
  },
  {
    type: "function",
    name: "whbarToken",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "address", name: "" }],
  },
  { type: "receive", stateMutability: "payable" },
] as const;

export default LotteryABI;
